AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*_spec.rb

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 12
