language: ruby

before_install:
  - gem update --system --no-document
  - gem install bundler

  - gem --version
  - bundle --version

bundler_args: --retry=3

cache: bundler

sudo: false

rvm:
  - 2.4.0
  - 2.4.4
  - 2.5.1
